// Copyright (C) 2026 Abdul, Hashim.
//
// This file is part of CARLA Studio.
// Licensed under the GNU Affero General Public License v3 or later -
// see <LICENSE> at the project root or
// <https://www.gnu.org/licenses/agpl-3.0.html> for the full text.
// SPDX-License-Identifier: AGPL-3.0-or-later

#include "vehicle/import/kit_bundler.h"

#include <QDir>
#include <QFile>
#include <QFileInfo>
#include <QJsonArray>
#include <QJsonDocument>
#include <QJsonObject>
#include <QSaveFile>
#include <QTextStream>

namespace carla_studio::vehicle_import {

QString render_kit_readme(const VehicleSpec &spec) {
  QString out;
  QTextStream s(&out);
  s << "# Vehicle Kit - " << spec.name << "\n\n";
  s << "Auto-generated by CARLA Studio. This kit contains everything you need to "
       "import this vehicle into a CARLA source build, with all CARLA-specific "
       "rules (bone names, physics damping, kinematic wheels, size-class presets) "
       "already encoded.\n\n";
  s << "## Files\n\n";
  s << "- `mesh.<ext>` - your source mesh (un-modified for now; Studio will canonicalize "
       "in slice 3).\n";
  s << "- `spec.json` - full canonical spec used by the UE plugin in Full mode. "
       "Every value below is derived from the mesh, no user inputs required.\n";
  s << "- `VehicleParameters.entry.json` - paste-ready JSON entry for "
       "`Content/Carla/Config/VehicleParameters.json` in your CARLA tree.\n";
  s << "- `README.md` - this file.\n\n";
  s << "## Detected vehicle profile\n\n";
  s << "| Field | Value |\n|---|---|\n";
  s << "| Name | `" << spec.name << "` |\n";
  s << "| Size class | `" << size_class_name(spec.size_class) << "` |\n";
  s << "| Mass | " << QString::number(spec.mass, 'f', 0) << " kg |\n";
  s << "| Suspension damping | " << QString::number(spec.susp_damping, 'f', 2) << " |\n";
  s << "| Torque-curve preset | `" << spec.torque_curve_tag << "` |\n";
  s << "| Chassis bbox (cm) | "
    << QString("X[%1..%2] Y[%3..%4] Z[%5..%6]")
         .arg(spec.chassis_x_min, 0, 'f', 1).arg(spec.chassis_x_max, 0, 'f', 1)
         .arg(spec.chassis_y_min, 0, 'f', 1).arg(spec.chassis_y_max, 0, 'f', 1)
         .arg(spec.chassis_z_min, 0, 'f', 1).arg(spec.chassis_z_max, 0, 'f', 1)
    << " |\n";
  s << "| Four-wheeled | " << (spec.has_four_wheels ? "yes" : "no") << " |\n";
  if (spec.small_vehicle_needs_wheel_shape)
    s << "| Note | wheel radius < 18 cm - Chaos vehicle physics needs a custom "
         "smaller `WheelShape` static mesh; the importer applies one automatically. |\n";
  s << "\n## Per-wheel measurements (cm, Unreal units)\n\n";
  s << "| Wheel | X | Y | Z | Radius | Width |\n|---|---|---|---|---|---|\n";
  static const char *names[4] = {"Front-Left", "Front-Right", "Rear-Left", "Rear-Right"};
  for (size_t i = 0; i < 4; ++i) {
    const WheelSpec &w = spec.wheels[i];
    s << "| " << names[i] << " | "
      << QString::number(w.x, 'f', 1) << " | "
      << QString::number(w.y, 'f', 1) << " | "
      << QString::number(w.z, 'f', 1) << " | "
      << QString::number(w.radius, 'f', 1) << " | "
      << QString::number(w.width, 'f', 1) << " |\n";
  }
  return out;
}

namespace {

QJsonObject vehicleParametersEntry(const VehicleSpec &spec) {
  QJsonObject e;
  e["Make"]              = QStringLiteral("Custom");
  e["Model"]             = spec.name;
  e["Class"] = QStringLiteral("/Game/Carla/Static/Vehicles/4Wheeled/") + spec.name +
               QStringLiteral("/BP_") + spec.name +
               QStringLiteral(".BP_") + spec.name + QStringLiteral("_C");
  e["NumberOfWheels"]    = 4;
  e["Generation"]        = 2;
  e["ObjectType"]        = QString();
  e["BaseType"]          = QStringLiteral("car");
  e["SpecialType"]       = QString();
  e["HasDynamicDoors"]   = false;
  e["HasLights"]         = false;
  e["RecommendedColors"] = QJsonArray();
  e["SupportedDrivers"]  = QJsonArray();
  return e;
}

bool writeText(const QString &path, const QString &text, KitBundleResult *r) {
  QSaveFile f(path);
  if (!f.open(QIODevice::WriteOnly | QIODevice::Text)) {
    if (r) r->detail = QStringLiteral("Cannot write %1").arg(path);
    return false;
  }
  f.write(text.toUtf8());
  if (!f.commit()) {
    if (r) r->detail = QStringLiteral("Failed to commit %1").arg(path);
    return false;
  }
  if (r) r->written_files << path;
  return true;
}

}

KitBundleResult write_vehicle_kit(const VehicleSpec &spec, const QString &output_dir) {
  KitBundleResult r;
  r.output_dir = output_dir;
  if (spec.name.isEmpty()) { r.detail = "Spec has no name."; return r; }
  if (!QDir().mkpath(output_dir)) { r.detail = "Cannot mkpath " + output_dir; return r; }

  const QString readme = render_kit_readme(spec);
  if (!writeText(output_dir + "/README.md", readme, &r)) return r;

  const QJsonObject spec_json = spec_to_json(spec);
  if (!writeText(output_dir + "/spec.json",
                 QString::fromUtf8(QJsonDocument(spec_json).toJson(QJsonDocument::Indented)),
                 &r)) return r;

  QJsonObject entryWrapper;
  QJsonArray vehicles;
  vehicles.append(vehicleParametersEntry(spec));
  entryWrapper["Vehicles"] = vehicles;
  if (!writeText(output_dir + "/VehicleParameters.entry.json",
                 QString::fromUtf8(QJsonDocument(entryWrapper).toJson(QJsonDocument::Indented)),
                 &r)) return r;

  if (!spec.mesh_path.isEmpty() && QFileInfo(spec.mesh_path).isFile()) {
    const QString ext = QFileInfo(spec.mesh_path).suffix().toLower();
    const QString dst = output_dir + "/mesh." + ext;
    QFile::remove(dst);
    if (QFile::copy(spec.mesh_path, dst)) r.written_files << dst;
  }

  r.ok = true;
  r.detail = QStringLiteral("Wrote %1 files to %2").arg(r.written_files.size()).arg(output_dir);
  return r;
}

}
